services:
  - type: web
    name: accessibility-prototype
    env: docker
    repo: https://github.com/Mugesh-lab/prototype
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    healthCheckPath: /
    autoDeploy: true
